### PR TITLE
ENG-1466: Pull in updates from upstream repo

### PR DESCRIPTION
**Pull request by artur-sak13**
## Description
Summary of changes:
* Remove Travis-CI pipeline in favor of GitHub Actions Workflow
* Rename scheduler tag variable name from `resources_tag` to `scheduler_tag`
* Changes to variable naming in Lambda function
* Bump minor version of Lambda function archive file (from `3.0.1 -> 3.1.3`)
* Bump versions of several Python package dependencies
* Rename `examples/instance-schedule` directory to `examples/instance-scheduler`
* Replace custom `lambda_logging_policy` with `AWSLambdaBasicExecutionRole` role policy attachment
* Fix `lambda_logging` role policy collision
* Add missing tags to AWS resources

## Motivation and Context
We haven't pulled in upstream changes since Nov 19, 2020, so this was due for an update.

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist
- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have linted my code locally prior to submission.
- [x] I have updated the documentation accordingly.

## Related ClickUp Task
[ENG-1446](https://app.clickup.com/t/2245946/ENG-1466)

### CODE REVIEW

**Comment by artur-sak13** [comment]
Task linked: [ENG-1466 Pull in upstream changes on twopt/terraform-aws-lambda-scheduler-stop-start](https://app.clickup.com/t/2245946/ENG-1466)

**Review by Andrew-Kulpa — APPROVED** [review]
LGTM, but I do see there is a merge conflict.

**Comment by artur-sak13** [comment]
> LGTM, but I do see there is a merge conflict.

Fixed. I'm gonna clean up my commits before merging and open a PR on the upstream repo.

**Review by bnweiss — APPROVED** [review]
Why do we need our own fork of this?

**Comment by artur-sak13** [comment]
> > LGTM, but I do see there is a merge conflict.
> 
> Fixed. I'm gonna clean up my commits before merging and open a PR on the upstream repo.

@Andrew-Kulpa nevermind. I ran into some issues with that fix. The merge conflict will have to be resolved manually while merging the PR.

**Comment by artur-sak13** [comment]
> Why do we need our own fork of this?

@bnweiss Thank you for asking this! We actually don't need it anymore! I was so focused on figuring out what to do about the merge conflict that I didn't stop to question whether this fork was still necessary. The reason I created this in the first place was to patch a permissions issue that was preventing the Lambda from creating CloudWatch log streams. The patch replaced the then broken `lambda_logging_policy` with the AWS managed service-role `AWSLambdaBasicExecutionRole`. 8461925 fixed the permissions issue and is actually better than what I changed a year ago because it scopes down the logging permissions to just the CloudWatch log group this module creates (`AWSLambdaBasicExecutionRole`'s scope is too permissive because it lets the Lambda create any kind of logging resources it wants).

**Comment by artur-sak13** [comment]
> > Why do we need our own fork of this?
> 
> @bnweiss Thank you for asking this! We actually don't need it anymore! I was so focused on figuring out what to do about the merge conflict that I didn't stop to question whether this fork was still necessary. The reason I created this in the first place was to patch a permissions issue that was preventing the Lambda from creating CloudWatch log streams. The patch replaced the then broken `lambda_logging_policy` with the AWS managed service-role `AWSLambdaBasicExecutionRole`. [8461925](https://github.com/twopt/terraform-aws-lambda-scheduler-stop-start/commit/8461925dd1842ebbe643bf33fbc1ae00630b75ba) fixed the permissions issue and is actually better than what I changed a year ago because it scopes down the logging permissions to just the CloudWatch log group this module creates (`AWSLambdaBasicExecutionRole`'s scope is too permissive because it lets the Lambda create any kind of logging resources it wants).

@Andrew-Kulpa are you cool with me closing this PR and replacing anything that's using this fork with the upstream module?

**Comment by Andrew-Kulpa** [comment]
> > > Why do we need our own fork of this?
> > 
> > 
> > @bnweiss Thank you for asking this! We actually don't need it anymore! I was so focused on figuring out what to do about the merge conflict that I didn't stop to question whether this fork was still necessary. The reason I created this in the first place was to patch a permissions issue that was preventing the Lambda from creating CloudWatch log streams. The patch replaced the then broken `lambda_logging_policy` with the AWS managed service-role `AWSLambdaBasicExecutionRole`. [8461925](https://github.com/twopt/terraform-aws-lambda-scheduler-stop-start/commit/8461925dd1842ebbe643bf33fbc1ae00630b75ba) fixed the permissions issue and is actually better than what I changed a year ago because it scopes down the logging permissions to just the CloudWatch log group this module creates (`AWSLambdaBasicExecutionRole`'s scope is too permissive because it lets the Lambda create any kind of logging resources it wants).
> 
> @Andrew-Kulpa are you cool with me closing this PR and replacing anything that's using this fork with the upstream module?

So sorry for not seeing this lol. Yes, definitely!

**Pull request closed without merging**
